// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cell_quantiles
NumericVector cell_quantiles(NumericMatrix mat, double prob);
RcppExport SEXP _LogicComm_cell_quantiles(SEXP matSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(cell_quantiles(mat, prob));
    return rcpp_result_gen;
END_RCPP
}
// fast_logic_scan
LogicalMatrix fast_logic_scan(NumericMatrix mat, NumericVector anchors);
RcppExport SEXP _LogicComm_fast_logic_scan(SEXP matSEXP, SEXP anchorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type anchors(anchorsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_logic_scan(mat, anchors));
    return rcpp_result_gen;
END_RCPP
}
// compute_lcs_knn
double compute_lcs_knn(LogicalVector ligand_logic, LogicalVector receptor_logic, IntegerVector knn_i, IntegerVector knn_j);
RcppExport SEXP _LogicComm_compute_lcs_knn(SEXP ligand_logicSEXP, SEXP receptor_logicSEXP, SEXP knn_iSEXP, SEXP knn_jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type ligand_logic(ligand_logicSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type receptor_logic(receptor_logicSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type knn_i(knn_iSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type knn_j(knn_jSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_lcs_knn(ligand_logic, receptor_logic, knn_i, knn_j));
    return rcpp_result_gen;
END_RCPP
}
// compute_lcs_global
double compute_lcs_global(LogicalVector ligand_logic, LogicalVector receptor_logic);
RcppExport SEXP _LogicComm_compute_lcs_global(SEXP ligand_logicSEXP, SEXP receptor_logicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type ligand_logic(ligand_logicSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type receptor_logic(receptor_logicSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_lcs_global(ligand_logic, receptor_logic));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LogicComm_cell_quantiles", (DL_FUNC) &_LogicComm_cell_quantiles, 2},
    {"_LogicComm_fast_logic_scan", (DL_FUNC) &_LogicComm_fast_logic_scan, 2},
    {"_LogicComm_compute_lcs_knn", (DL_FUNC) &_LogicComm_compute_lcs_knn, 4},
    {"_LogicComm_compute_lcs_global", (DL_FUNC) &_LogicComm_compute_lcs_global, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_LogicComm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
