# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute per-cell expression quantile anchors
#'
#' For each cell (column), computes the quantile of expressed (non-zero)
#' gene values. This serves as the dynamic background anchor for REO conversion.
#'
#' @param mat A numeric matrix (genes x cells).
#' @param prob Quantile probability, e.g. 0.5 for median. Default: 0.5.
#' @return Numeric vector of length ncol(mat), one anchor per cell.
cell_quantiles <- function(mat, prob = 0.5) {
    .Call(`_LogicComm_cell_quantiles`, mat, prob)
}

#' Fast binary logic scan (REO conversion)
#'
#' Converts a gene expression matrix to a logical 0/1 matrix by comparing
#' each cell's gene values against that cell's dynamic anchor.
#'
#' @param mat A numeric matrix (genes x cells).
#' @param anchors A numeric vector of per-cell thresholds (length = ncols).
#' @return A logical matrix (genes x cells); TRUE where expression > anchor.
fast_logic_scan <- function(mat, anchors) {
    .Call(`_LogicComm_fast_logic_scan`, mat, anchors)
}

#' Compute KNN-based Logic Consensus Score (LCS)
#'
#' For each ligand-receptor pair, counts directed KNN edges where the sender
#' cell expresses the ligand above anchor AND the receiver cell expresses the
#' receptor above anchor.
#'
#' @param ligand_logic Logical vector (length = n_cells): TRUE if cell expresses ligand.
#' @param receptor_logic Logical vector (length = n_cells): TRUE if cell expresses receptor.
#' @param knn_i Integer vector of sender cell indices (1-based), from sparse KNN matrix.
#' @param knn_j Integer vector of receiver cell indices (1-based).
#' @return Numeric scalar: fraction of active KNN directed edges.
compute_lcs_knn <- function(ligand_logic, receptor_logic, knn_i, knn_j) {
    .Call(`_LogicComm_compute_lcs_knn`, ligand_logic, receptor_logic, knn_i, knn_j)
}

#' Compute global co-expression Logic Consensus Score (no KNN)
#'
#' Fraction of cells that co-express both ligand and receptor above anchor.
#' This is the "global mode" LCS (no spatial/neighborhood constraint).
#'
#' @param ligand_logic Logical vector: TRUE if cell expresses ligand.
#' @param receptor_logic Logical vector: TRUE if cell expresses receptor.
#' @return Numeric scalar: fraction of cells co-expressing both.
compute_lcs_global <- function(ligand_logic, receptor_logic) {
    .Call(`_LogicComm_compute_lcs_global`, ligand_logic, receptor_logic)
}

